### ISSUE TITLE
GPU usage ?

### ISSUE THREAD

**Issue by Cloud299** [ina-foss/inaSpeechSegmenter#11]
How can I run this segmentation on GPU instead of CPU for faster processing ? 
Is there an API for this ?

**Comment by DavidDoukhan** [comment]
You need to install tensorflow-gpu pip module
This is detailed in the README.md in section "PIP installation"
If you still experience issues with the use of GPU, please have a look to tensorflow documentation.
Regards,

**Comment by Cloud299** [comment]
Thank you for the response. Could you provide the versions #  for the following:
tensorflow-gpu
keras
cuda
cudnn
