### ISSUE TITLE
Win10 Py 3.5: Impossible to use PyTorch

### ISSUE THREAD

**Issue by Waprog** [ina-foss/inaSpeechSegmenter#13]
Hi,

Here are my specifications:
Win10 64-Bit
Python 3.5.0
pip 19.0.3

I am trying to use inaSpeechSegmenter but I am unable to do so because of PyTorch. 
I've searched on the internet to manually install, which I finally did, but it is still not working.

The error is :
```
    import torch
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35\lib\site-packages\torch\__init__.py", line 102, in <module>
    from torch._C import *
ImportError: DLL load failed: Le module spécifié est introuvable.
```

Does anyone have any idea what to do?

Thanks for the help.

**Comment by DavidDoukhan** [comment]
Dear Waprog,
I did a small fix that will hopefully fix this issue.
Could you try the updated version of inaspeechsegmenter and let me know if this allowed to solve this problem?
Regards,

**Comment by Waprog** [comment]
Hi David,

I'll get back to you tomorrow see if everything works now.
Thank you and have a good day.

*Alexandre Paradis*
Développeur Web / Sound Designer
alexandreparadis.com


Le lun. 15 avr. 2019 à 11:03, David Doukhan <notifications@github.com> a
écrit :
