### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by JaredCE** [ina-foss/inaSpeechSegmenter#18]
It'd be nice to see some pytest (or whichever your favourite python testing framework might be) tests added to the repo.

**Comment by DavidDoukhan** [comment]
True!

Feel free to contribute and propose some tests for this framework!

Regards,

**Comment by DavidDoukhan** [comment]
Dear JaredCE, i've added some unittests.
These allow to highlight some minor bug to be fixed soon.
Feel free to add some more.
Kind regards,
