### ISSUE TITLE
something about training features

### ISSUE THREAD

**Issue by lyu-joe** [ina-foss/inaSpeechSegmenter#19]
hi,
     i have read the paper which the project cited ， but  in the paper it tells me you trained the model using mfcc features ，you use melspec in the segment.py 's _wav2feats  ,so  what exactly features you’ve trained the models

**Comment by DavidDoukhan** [comment]
Hi,

As you noticed, the feature we used are Mel Log Spetrograms, in our ICASSP paper we called them "24 Mel-scaled ﬁlter-banks coefﬁcients". We did use MFCC in other methods (GMM, ivector-based) that were compared to the CNN model provided in this framework. 
GMM and I-vector models described in the paper are not provided in this framework.

Regards,
