### ISSUE TITLE
Any improvements plan?

### ISSUE THREAD

**Issue by lvaleriu** [ina-foss/inaSpeechSegmenter#2]
I forgot to congratulate you for this nice project! So 'im doing it right now. You've done a very nice job.
Is there any plan to improve this project so that contributers can help?

**Comment by DavidDoukhan** [comment]
Dear Valeriu,

Thank you for this positive feedback!

Right now we're working on asynchronous feature extraction: this will be integrated to our project in the next few days, thanks to the contributions of @elechapt .

Some work may be done in the reimplementation way models are used. Right now, subsegments are extracted on the fly, and consequently the GPU are not used at a 100% rate. I guess this may be improved and allow to perform faster extraction. If you think you may have some time to look at it this would be very welcome!

Ongoing work consist in improving the activity detection procedure, which is currently only based on energetic activity.

Another good way to help us improving this software is to submit us examples which are associated to bad performances, as well as data that could be used to train better models!

Lastly, a good way to help the long term improvement of this software would be to propose alternative neural architectures; and/or to compare the performances of alternative systems to this software!

Thanks!

**Comment by lvaleriu** [comment]
* Wait to see the @elechapt contribution related to the asynchronous feature extraction
* I might try to take a look on the extraction of subsegments. I'll notice you if I find a path of improvement
* Concerning the "activity detection procedure": do you mean detecting when there is real noise as opposed to silence / or inaudible background noise?
* I'm currently testing your trained model on data. So far all seems pretty good, but as soon as I find bad performances I'll send you some examples
* I have some arhitectures (time-variant & time-invariant classification models) in mind (https://github.com/keunwoochoi/kapre, https://github.com/keunwoochoi/dl4mir -> more suited maybe for music classification) but is there any public dataset available?
