### ISSUE TITLE
AttributeError: module 'distutils' has no attribute 'util

### ISSUE THREAD

**Issue by jasonblog** [ina-foss/inaSpeechSegmenter#22]
I am using the latest version with an error message

```
    detect_gender = bool(distutils.util.strtobool(args.detect_gender))
AttributeError: module 'distutils' has no attribute 'util

```

Add below code to solve in ina_speech_segmenter.py
from distutils import util

**Comment by DavidDoukhan** [comment]
Dear @jasonblog ,
Thanks for your message.
I would need additional information in order to fix this issue.

Could you provide me the following information on your configuration?
I would need:

* python version
* operating system
* method used for the installation of the software
* python modules installed (output of pip freeze)

Kind regards,

**Comment by DavidDoukhan** [comment]
Dear @jasonblog,
I would be very glad to have some more details on your configuration.
Kind regards,

My current configuration, which works fine is the following:
* python 3.5.2
* Linux lucrate-titan 4.15.0-66-generic #75~16.04.1-Ubuntu SMP Tue Oct 1 14:01:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* software installed using pip repository: `pip install inaspeechsegmenter tensorflow`
* ```
ddoukhan@lucrate-titan:/tmp$ pip freeze
absl-py==0.8.1
astor==0.8.0
cachetools==3.1.1
certifi==2019.9.11
chardet==3.0.4
cycler==0.10.0
decorator==4.4.1
docopt==0.6.2
gast==0.2.2
google-auth==1.7.0
google-auth-oauthlib==0.4.1
google-pasta==0.1.8
grpcio==1.25.0
h5py==2.10.0
idna==2.8
imageio==2.6.1
inaSpeechSegmenter==0.3.2
joblib==0.14.0
Keras==2.3.1
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
kiwisolver==1.1.0
Markdown==3.1.1
matplotlib==3.0.3
mock==3.0.5
munkres==1.1.2
networkx==2.4
nose==1.3.7
numpy==1.17.4
oauthlib==3.1.0
opt-einsum==3.1.0
pandas==0.24.2
Pillow==6.2.1
pkg-resources==0.0.0
protobuf==3.10.0
pyannote.algorithms==0.8
pyannote.core==3.0
pyannote.parser==0.7.1
pyasn1==0.4.7
pyasn1-modules==0.2.7
pyparsing==2.4.5
python-dateutil==2.8.1
pytz==2019.3
PyWavelets==1.1.1
PyYAML==5.1.2
requests==2.22.0
requests-oauthlib==1.3.0
rsa==4.0
scikit-image==0.15.0
scikit-learn==0.21.3
scipy==1.3.2
SIDEKIT==1.2.4
simplejson==3.16.0
six==1.13.0
sortedcollections==1.1.2
sortedcontainers==2.1.0
tensorboard==2.0.1
tensorflow==2.0.0
tensorflow-estimator==2.0.1
termcolor==1.1.0
Theano==1.0.4
urllib3==1.25.7
Werkzeug==0.16.0
wrapt==1.11.2
xarray==0.12.3
```

**Comment by jasonblog** [comment]
Python 3.7.3  using  anaconda3

Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic



absl-py==0.8.1
alabaster==0.7.12
anaconda-client==1.7.2
anaconda-navigator==1.9.7
anaconda-project==0.8.2
arrow==0.14.2
asn1crypto==0.24.0
astor==0.8.0
astroid==2.2.5
astropy==3.1.2
atomicwrites==1.3.0
attrs==19.1.0
Babel==2.6.0
backcall==0.1.0
backports.os==0.1.1
backports.shutil-get-terminal-size==1.0.0
beautifulsoup4==4.7.1
bitarray==0.8.3
bkcharts==0.2
bleach==3.1.0
bokeh==1.0.4
boto==2.49.0
Bottleneck==1.2.1
certifi==2019.3.9
cffi==1.12.2
chardet==3.0.4
Click==7.0
cloudpickle==0.8.0
clyent==1.2.2
colorama==0.4.1
conda==4.6.11
conda-build==3.17.8
conda-verify==3.1.1
contextlib2==0.5.5
cryptography==2.6.1
cycler==0.10.0
Cython==0.29.6
cytoolz==0.9.0.1
dask==1.1.4
dateparser==0.7.1
decorator==4.4.0
defusedxml==0.5.0
distributed==1.26.0
docopt==0.6.2
docutils==0.14
docx==0.2.4
entrypoints==0.3
et-xmlfile==1.0.1
fastcache==1.0.2
filelock==3.0.10
Flask==1.0.2
flit==1.3
future==0.17.1
gast==0.2.2
gevent==1.4.0
glob2==0.6
gmpy2==2.0.8
google-pasta==0.1.7
greenlet==0.4.15
grpcio==1.24.1
h5py==2.9.0
heapdict==1.0.0
html5lib==1.0.1
idna==2.8
imageio==2.5.0
imagesize==1.1.0
importlib-metadata==0.0.0
inaSpeechSegmenter==0.1.1
ipykernel==5.1.0
ipython==7.4.0
ipython-genutils==0.2.0
ipywidgets==7.4.2
isort==4.3.16
itsdangerous==1.1.0
jdcal==1.4
jedi==0.13.3
jeepney==0.4
Jinja2==2.10
joblib==0.14.0
jsonschema==3.0.1
jupyter==1.0.0
jupyter-client==5.2.4
jupyter-console==6.0.0
jupyter-core==4.4.0
jupyterlab==0.35.4
jupyterlab-server==0.2.0
Keras==2.3.1
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
keyring==18.0.0
kiwisolver==1.0.1
lazy-object-proxy==1.3.1
libarchive-c==2.8
lief==0.9.0
llvmlite==0.28.0
locket==0.2.0
lxml==4.3.2
Markdown==3.1.1
MarkupSafe==1.1.1
matplotlib==3.0.3
mccabe==0.6.1
mistune==0.8.4
mkl-fft==1.0.10
mkl-random==1.0.2
mock==3.0.5
moment==0.8.2
more-itertools==6.0.0
mpmath==1.1.0
msgpack==0.6.1
multipledispatch==0.6.0
munkres==1.1.2
navigator-updater==0.2.1
nbconvert==5.4.1
nbformat==4.4.0
networkx==2.2
nltk==3.4
nose==1.3.7
notebook==5.7.8
numba==0.43.1
numexpr==2.6.9
numpy==1.16.2
numpydoc==0.8.0
olefile==0.46
opencv-python==4.1.1.26
openpyxl==2.6.1
opt-einsum==3.1.0
packaging==19.0
pandas==0.24.2
pandocfilters==1.4.2
parso==0.3.4
partd==0.3.10
path.py==11.5.0
pathlib2==2.3.3
patsy==0.5.1
pep8==1.7.1
pexpect==4.6.0
pickleshare==0.7.5
Pillow==5.4.1
pkginfo==1.5.0.1
pluggy==0.9.0
ply==3.11
prometheus-client==0.6.0
prompt-toolkit==2.0.9
protobuf==3.10.0
psutil==5.6.1
ptyprocess==0.6.0
py==1.8.0
pyannote.algorithms==0.8
pyannote.core==3.0
pyannote.parser==0.7.1
pycodestyle==2.5.0
pycosat==0.6.3
pycparser==2.19
pycrypto==2.6.1
pycurl==7.43.0.2
pydub==0.23.1
pyflakes==2.1.1
Pygments==2.3.1
pylint==2.3.1
pymt5==1.2.0
PyMySQL==0.9.3
pyodbc==4.0.26
pyOpenSSL==19.0.0
pyparsing==2.3.1
pyrsistent==0.14.11
PySocks==1.6.8
pytest==4.3.1
pytest-arraydiff==0.3
pytest-astropy==0.5.0
pytest-doctestplus==0.3.0
pytest-openfiles==0.3.2
pytest-remotedata==0.3.1
python-dateutil==2.8.0
pytoml==0.1.21
pytz==2018.9
PyWavelets==1.0.2
PyYAML==5.1
pyzmq==18.0.0
QtAwesome==0.5.7
qtconsole==4.4.3
QtPy==1.7.0
regex==2019.6.8
requests==2.21.0
rope==0.12.0
ruamel-yaml==0.15.46
scikit-image==0.14.2
scikit-learn==0.20.3
scipy==1.2.1
seaborn==0.9.0
SecretStorage==3.1.1
Send2Trash==1.5.0
SIDEKIT==1.2.4
simplegeneric==0.8.1
simplejson==3.16.0
singledispatch==3.4.0.3
six==1.12.0
snowballstemmer==1.2.1
sortedcollections==1.1.2
sortedcontainers==2.1.0
soupsieve==1.8
Sphinx==1.8.5
sphinxcontrib-websupport==1.1.0
spyder==3.3.3
spyder-kernels==0.4.2
SQLAlchemy==1.3.1
statsmodels==0.9.0
sympy==1.3
TA-Lib==0.4.17
tables==3.5.1
tblib==1.3.2
tensorboard==2.0.0
tensorflow==2.0.0
tensorflow-estimator==2.0.0
tensorflow-gpu==2.0.0
termcolor==1.1.0
terminado==0.8.1
testpath==0.4.2
Theano==1.0.4
times==0.7
toolz==0.9.0
tornado==6.0.2
tqdm==4.31.1
traitlets==4.3.2
twstock==1.1.2
tzlocal==1.5.1
unicodecsv==0.14.1
urllib3==1.24.1
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==0.14.1
widgetsnbextension==3.4.2
wrapt==1.11.1
wurlitzer==1.0.2
xarray==0.13.0
xlrd==1.2.0
XlsxWriter==1.1.5
xlwt==1.3.0
zict==0.1.4
zipp==0.3.3

**Comment by DavidDoukhan** [comment]
This issue was related with python version used and is now fixed.
Thanks for your report!
