### ISSUE TITLE
What if gender identification is time consuming

### ISSUE THREAD

**Issue by lzj520** [ina-foss/inaSpeechSegmenter#23]
What if gender identification is time consuming

**Comment by DavidDoukhan** [comment]
Hi Lz520,

Gender identification step can be skipped using constructor option detect_gender = False.
There is always trade-offs to be done between execution time and system accuracy.
In InaSpeechSegmenter, we choosed to focus on system accuracy.
I you wish faster models, I could suggest using GMM-based systems.

Kind regards,
