### ISSUE TITLE
Memory grows with each execution and is not freed

### ISSUE THREAD

**Issue by lzj520** [ina-foss/inaSpeechSegmenter#24]
Memory grows with each execution and is not freed

**Comment by DavidDoukhan** [comment]
Hi Lzj520,

Thanks for your feedback.
Could you provide me more details on your configuration, in order to make your issue reproductible?

I would need the following informations:

## Step to reproduce


1. Installed using `...`
2. Run as `...`
3. Got `...` error


## Environment
OS
Installation type (Conda, pip, other)
Hardware spec (GPU / CPU / etc ... )
Python version

## Additional context



Kind regards,

**Comment by lzj520** [comment]
Memory unfreed

python3.5 + gunicorn+flask
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"David Doukhan"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月2日(星期一) 晚上8:48
收件人:&nbsp;"ina-foss/inaSpeechSegmenter"<inaSpeechSegmenter@noreply.github.com&gt;;
抄送:&nbsp;"$天授*"<527263822@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ina-foss/inaSpeechSegmenter] Memory grows with each execution and is not freed (#24)




Hi Lzj520,
 
Thanks for your feedback.
 Could you provide me more details on your configuration, in order to make your issue reproductible?
 
I would need the following informations:
 
Step to reproduce
  
Installed using ...
 
Run as ...
 
Got ... error
  
Environment
 
OS
 Installation type (Conda, pip, other)
 Hardware spec (GPU / CPU / etc ... )
 Python version
 
Additional context
 
Kind regards,

**Comment by lzj520** [comment]
Memory unfreed
Line #    Mem usage    Increment   Line Contents
================================================
    13    104.7 MiB    104.7 MiB   @profile
    14                             def get_voice_ratedata(wavname):
    15    104.7 MiB      0.0 MiB       try:
    16    106.4 MiB      1.7 MiB           sig, read_framerate = librosa.load(wavname, sr=16000)
    17    106.4 MiB      0.0 MiB           print('sig', sys.getrefcount(sig))
    18    106.4 MiB      0.0 MiB           print('read_framerate', sys.getrefcount(read_framerate))
    19    106.4 MiB      0.0 MiB           return sig, read_framerate
    20                                 finally:
    21    106.4 MiB      0.0 MiB           del sig,read_framerate
    22    106.4 MiB      0.0 MiB           gc.collect()


model name      : Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz
model name      : Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz
model name      : Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz
model name      : Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz

flask+gunicorn+gevent+python3+liunx

**Comment by DavidDoukhan** [comment]
Dear Lzj520,

inaSpeechSegmenter is not based on librosa.
It seems the code you're showing does not belong to inaSpeechSegmenter, and do not make use of inaSpeechSegmenter.
I cannot help you based on this bug description.

Kind regards,
