### ISSUE TITLE
run detect very slow

### ISSUE THREAD

**Issue by dangvansam98** [ina-foss/inaSpeechSegmenter#28]
i run inaSpeechSegmenter python code to detect voice in file. it take a long time (about 10min/file).
so how can improve speed for detect file
![image](https://user-images.githubusercontent.com/45785880/71759193-e735ce00-2edb-11ea-912f-362ed7eb2eda.png)
thanks!

**Comment by DavidDoukhan** [comment]
Duplicate https://github.com/ina-foss/inaSpeechSegmenter/issues/9
