### ISSUE TITLE
Any way to detect sentences?

### ISSUE THREAD

**Issue by george-roussos** [ina-foss/inaSpeechSegmenter#32]
I am on about speakers (more specifically narrators) that do not pay attention to phrase break durations; I would only like to split on full sentences and these are almost always longer. Does a higher bitrate sound file help?

**Comment by DavidDoukhan** [comment]
Thanks for your interest.
This software is not intented to manage sentences.
However, its used may be combined with ASR systems in charge of predicting sentences.
Kind regards,
