### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by ucas010** [ina-foss/inaSpeechSegmenter#33]
hi,dear
OS:win10
when I use pip install the inaSpeechSegmenter,
ups error
```
ERROR: Could not find a version that satisfies the requirement torch>=1.0 (from sidekit) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch>=1.0 (from sidekit)
```
so how to solve it?
thx

**Comment by DavidDoukhan** [comment]
Could you tell me which python version you are using ?

**Comment by ucas010** [comment]
@DavidDoukhan 
hi,after I install torch,solved the problem,
thx
