### ISSUE TITLE
Sidekit

### ISSUE THREAD

**Issue by jainshubham1120** [ina-foss/inaSpeechSegmenter#34]
I  have installed sidekit using pip and tried running it on spyder(Anaconda). Still it is showing - No module named 'sidekit'. Can you help?

**Comment by DavidDoukhan** [comment]
Dear @jainshubham1120 ,

This question is out of the scope of inaSpeechSegmenter and should be addressed to sidekit developpers:
https://git-lium.univ-lemans.fr/Larcher/sidekit

Kind regards,
