### ISSUE TITLE
Control granularity of speech segments

### ISSUE THREAD

**Issue by doodlesbykumbi** [ina-foss/inaSpeechSegmenter#35]
I wonder if it would be possible to make the speech segments more granular or have control of the granularity? At present it seems that lengthy periods of speech (e.g. sentences) are bundled up into one. I'm looking for segmentation at the word level.

**Comment by DavidDoukhan** [comment]
Dear @doodlesbykumbi, inaSpeechSegmenter is not intended for word-level segmentation.
For such-use case, you need to use speech-to-text softwares.
However, inaSpeechSegmenter can be used as a preprocessing step in a speech-to-text pipeline:
inaSpeechSegmenter -> Speaker Diarization ->Speech Recognition
Kind regards,

**Comment by doodlesbykumbi** [comment]
Thanks @DavidDoukhan. It turns out the challenge I was alluding to (irrespective of granularity) is known as forced alignment. I found a treasure trove of prior work that performs quite well on the task, https://github.com/pettarin/forced-alignment-tools.
