### ISSUE TITLE
Could I specify the GPU ??

### ISSUE THREAD

**Issue by ucas010** [ina-foss/inaSpeechSegmenter#37]
hi,dear
I want to specify the GPU for the seg?
could you help me ?
thx

**Comment by DavidDoukhan** [comment]
Dear @ucas010 , this is a tensorflow question.
You need to set CUDA_VISIBLE_DEVICES environment variable. https://riptutorial.com/tensorflow/example/31877/use-a-particular-set-of-gpu-devices
Kind regardss,
