### ISSUE TITLE
how to classify speech and speech over music？

### ISSUE THREAD

**Issue by nekoneYuzu** [ina-foss/inaSpeechSegmenter#4]

**Comment by DavidDoukhan** [comment]
Hi,
In the current version of the framework, speech over music is classified as speech.
No distinction is done between speech and speech over music.
Regards,

**Comment by anavc94** [comment]
Hello,

I want to segment speech over music and music, are there any plans of release the train script in order to retrain the model with 'speech over music' class? 

Thanks a lot
