### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by tomjerrygithub** [ina-foss/inaSpeechSegmenter#42]
Line #    Mem usage    Increment   Line Contents
================================================
     6    363.0 MiB    363.0 MiB   @profile
     7                             def test():
     8                                 
     9    363.0 MiB      0.0 MiB       media = '8560_00.mp4'
    10                             
    11    710.4 MiB    347.4 MiB       segmentation = seg(media)
    12                                 
    13    710.4 MiB      0.0 MiB       print(segmentation)

Line #    Mem usage    Increment   Line Contents
================================================
     6    937.0 MiB    937.0 MiB   @profile
     7                             def test():
     8                                 
     9    937.0 MiB      0.0 MiB       media = '8560_00.mp4'
    10                             
    11   1086.5 MiB    149.6 MiB       segmentation = seg(media)
    12                                 
    13   1086.5 MiB      0.0 MiB       print(segmentation)

Line #    Mem usage    Increment   Line Contents
================================================
     6   1498.8 MiB   1498.8 MiB   @profile
     7                             def test():
     8                                 
     9   1498.8 MiB      0.0 MiB       media = '8560_00.mp4'
    10                             
    11   1613.3 MiB    114.5 MiB       segmentation = seg(media)
    12                                 
    13   1613.3 MiB      0.0 MiB       print(segmentation)

`
from inaSpeechSegmenter import Segmenter, seg2csv
from memory_profiler import profile

seg = Segmenter(vad_engine='smn',detect_gender=False)

@profile
def test():
    
    media = '8560_00.mp4'

    segmentation = seg(media)
    
    print(segmentation)
    

for i in range(10):
    test()
`

python 3.7.3
tensorflow  2.2.0
keras 2.4.3

**Comment by DavidDoukhan** [comment]
Dear @tomjerrygithub ,

These issues were due to changes in tensorflow behavior.
These have been fixed.
