### ISSUE TITLE
Regarding its use in other domains

### ISSUE THREAD

**Issue by saurabh2811** [ina-foss/inaSpeechSegmenter#44]
how we can use that for other purpose

**Comment by saurabh2811** [comment]
means how we can segment known speakers by using this (known speaker segmentation)

**Comment by r-uro** [comment]
Hi @saurabh2811 
I don't think inaSpeechSegmenter should be used for such purposes. It could be used as preprocessing for a diarization task, but I suggest you look for a system actually made for speaker diarization instead. Maybe this repo can help you find what you want : https://github.com/wq2012/awesome-diarization

Best,

**Comment by DavidDoukhan** [comment]
Thanks @r-uro for these clarifications.
