### ISSUE TITLE
Not able to install ffmpeg

### ISSUE THREAD

**Issue by YatinMahajann** [ina-foss/inaSpeechSegmenter#58]
Hi There,

I am not able to install ffmpeg on my system. I am using Ubuntu 19.04. ANd as mentioned in the description, I tried Installing ffmpeg from this command : $ sudo apt-get install ffmpeg. But got an error that "_**E: Package 'ffmpeg' has no installation candidate**_"

However as mentioned in the description we can pass binaries for ffmpeg as well. Could you please let me know how can we do that. I tried running below after downloading the binaries for ubuntu:
**seg = Segmenter(detect_gender=False, ffmpeg= "/Home/Downloads/ffmpeg-4.2.1-linux-64")**
But got an error message :
**Exception: ffmpeg program not found**

Your help would be much appreciated. Thanks in Advance!

**Comment by keighrim** [comment]
You probably need to `sudo apt-get update` first to download all available apps from the server before trying to install any. However 19.04 had already reached its end of life (over a year ago), so the server is not likely to respond. Please consider upgrading to a long-term support version (20.04).

**Comment by DavidDoukhan** [comment]
Dear @YatinMahajann ,

Could you type the following command in your terminal in order to check your path to ffmpeg is valid ?
`ls "/Home/Downloads/ffmpeg-4.2.1-linux-64"`

My feeling is that you used a capital letter for '/Home' instead of '/home'

Kind regards,

**Comment by YatinMahajann** [comment]
Thanks @keighrim @DavidDoukhan for your support . Updating the Ubuntu to latest version and then installing all the files resolved the issue. Also as mentioned by @DavidDoukhan the path of file should start with '/home'. It was an error in copy/pasting from my side.

Thanks Again!
