### ISSUE TITLE
tensorflow.compat.v2 has no attribute '__internal__'

### ISSUE THREAD

**Issue by lfgogogo** [ina-foss/inaSpeechSegmenter#59]
I install tensorflow2.2.0 and inaSS,when i run ina_speech_segmenter.py,i get an error caused by 'import keras',details are in below,anyone knows why plz help me,thanks!

**Comment by tann9949** [comment]
edit source code in `segmenter.py`. Change `import keras` to `from tensorflow import keras`

**Comment by DavidDoukhan** [comment]
Dear @lfgogogo ,

I've just merged @tann9949 suggestion to the master.

Thanks to both of you for helping in the maintenance of this software !
