### ISSUE TITLE
Problems in MS Windows

### ISSUE THREAD

**Issue by ritalexoliveira** [ina-foss/inaSpeechSegmenter#6]
Hi!

I have problems with inaspeechsegmenter in Windows, because the input path cannot be found. 

![prtsrc](https://user-images.githubusercontent.com/40802180/42593018-36696d04-8543-11e8-9689-fbb0e7361131.PNG)

How can I fix this problem?

Thanks in advance,
Rita

**Comment by DavidDoukhan** [comment]
Dear Rita,

I think this bug may be related to ffmpeg.
Do you have ffmpeg installed on your machine?

Could you type "ffmpeg" in the command prompt and provide me the associated output?

Regards,

**Comment by DavidDoukhan** [comment]
I've just did small modifications to make the program check for ffmpeg and output an explicit message if this program is missing.
Please try the new version, and let me know if there are still issues.
Regards,
