### ISSUE TITLE
Provide draft code for training a model

### ISSUE THREAD

**Issue by realies** [ina-foss/inaSpeechSegmenter#62]
There are a lot of issues related to questions on how to train a custom model, and requests for a script to train own models.

Would it be possible for the R&D team behind this project to provide the draft code used to train its model in some form, without the actual dataset? It would be very useful for creating a contribution adding training code for inaSpeechSegmenter.

https://github.com/ina-foss/inaSpeechSegmenter/issues/48
https://github.com/ina-foss/inaSpeechSegmenter/issues/41
https://github.com/ina-foss/inaSpeechSegmenter/issues/12
https://github.com/ina-foss/inaSpeechSegmenter/issues/5
https://github.com/ina-foss/inaSpeechSegmenter/issues/4

**Comment by DavidDoukhan** [comment]
The amount of word required to provide the training code is too important and I'm lazy
This may be done for the release of future inference models.
Kind regards,

**Comment by realies** [comment]
@DavidDoukhan, that's great... :):) Would you mind sanity-checking an implementation of the training code if there's a PR?
