### ISSUE TITLE
Score for gender prediction

### ISSUE THREAD

**Issue by morShamy** [ina-foss/inaSpeechSegmenter#66]
Is there an option to receive a score (probability) for the gender prediction, and not just binary classification?

**Comment by DavidDoukhan** [comment]
Dear @morShamy ,
There is an option allowing to get gender probability for each detected segment.

While this option has not been integrated to the master project, you can access it within the mf_proba branch of the project : 
https://github.com/ina-foss/inaSpeechSegmenter/tree/mf_proba

The tutorial notebook of this branch show how to use it : 
https://github.com/ina-foss/inaSpeechSegmenter/blob/mf_proba/API_Tutorial.ipynb

Kind regards,
