### ISSUE TITLE
Docker container: NVIDIA key change, use with Jupyter

### ISSUE THREAD

**Issue by wbailer** [ina-foss/inaSpeechSegmenter#71]
Thanks for providing this tool.

There seems to be a change in NVIDIA GPG keys, that breaks the TF 2.7 base image you are using (resulting in error messages of apt-get update).

Here is a fix from https://github.com/NVIDIA/nvidia-docker/issues/1631#issuecomment-1112828208 that worked for me (adding those lines before the block of apt-get commands):

RUN rm /etc/apt/sources.list.d/cuda.list
RUN rm /etc/apt/sources.list.d/nvidia-ml.list
RUN apt-key del 7fa2af80
RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/3bf863cc.pub
RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/7fa2af80.pub

As you provide a Jupyter file to test your tool, you could also add the following line at the end of the Dockerfile to start up with the right notebook directory:

CMD /bin/bash -c "source /etc/bash.bashrc && jupyter notebook --notebook-dir=/inaSpeechSegmenter --ip 0.0.0.0 --no-browser --allow-root"

Best regards,
Werner

**Comment by DavidDoukhan** [comment]
Dear @wbailer , @simonD3V did changes to the Dockerfile allowing to get rid of the error messages.
Kind regards,
