### ISSUE TITLE
problem with ffmpg

### ISSUE THREAD

**Issue by felixbur** [ina-foss/inaSpeechSegmenter#78]
Please fill out this template for a bug report.

Make sure you ran the unit tests before submitting an issue and tell us if and where they fail.

## System information
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Ubuntu 20
-
- TensorFlow version:
- Python version:3.8.10
-
- Running on GPU or CPU:
cpu 

- Using Docker: 

## System information required if using GPU acceleration
- output of command `nvidia-smi` : 
- output of command `python3 -c "import tensorflow as tf; print(tf.sysconfig.get_build_info()); print(tf.config.list_physical_devices('GPU'))"` :
- CUDA/cuDNN version :

## Current Behavior

File [~/research/tmp/inaspeech_segmenter/venv/lib/python3.8/site-packages/inaSpeechSegmenter/segmenter.py:278](https://file+.vscode-resource.vscode-cdn.net/home/audeering.local/fburkhardt/research/tmp/inaspeech_segmenter/~/research/tmp/inaspeech_segmenter/venv/lib/python3.8/site-packages/inaSpeechSegmenter/segmenter.py:278), in Segmenter.__call__(self, medianame, tmpdir, start_sec, stop_sec)
...
---> 94 assert p.returncode == 0, error
     96 # Get Mel Power Spectrogram and Energy
     97 return _wav2feats(tmpwav)

AssertionError: b'ffmpeg version 4.2.7-0ubuntu0.1 Copyright (c) 2000-2022 the FFmpeg developers\n  built with gcc 9 (Ubuntu 9.4.0-1ubuntu1~20.04.1)\n  configuration: --prefix=/usr --extra-version=0ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared\n  libavutil      56. 31.100 [/](https://file+.vscode-resource.vscode-cdn.net/) 56. 31.100\n  libavcodec     58. 54.100 [/](https://file+.vscode-resource.vscode-cdn.net/) 58. 54.100\n  libavformat    58. 29.100 [/](https://file+.vscode-resource.vscode-cdn.net/) 58. 29.100\n  libavdevice    58.  8.100 [/](https://file+.vscode-resource.vscode-cdn.net/) 58.  8.100\n  libavfilter     7. 57.100 [/](https://file+.vscode-resource.vscode-cdn.net/)  7. 57.100\n  libavresample   4.  0.  0 [/](https://file+.vscode-resource.vscode-cdn.net/)  4.  0.  0\n  libswscale      5.  5.100 [/](https://file+.vscode-resource.vscode-cdn.net/)  5.  5.100\n  libswresample   3.  5.100 [/](https://file+.vscode-resource.vscode-cdn.net/)  3.  5.100\n  libpostproc    55.  5.100 [/](https://file+.vscode-resource.vscode-cdn.net/) 55.  5.100\nn: No such file or directory\n'

## Steps to Reproduce

1.
2.
3.
4.

**Comment by bagustris** [comment]
@felixbur 
I believe this error due to typo on audio file name (see the last error message: `No such file or directory`). For instance, if I change the filename from `musanmix.mp3` to `musanmi.mp3` in the [example](https://github.com/ina-foss/inaSpeechSegmenter/blob/master/tutorials/API_Tutorial.ipynb), I got the same error message.

**Comment by felixbur** [comment]
confirmed, it was a wrong path and nothing to do with ffmpeg
