### ISSUE TITLE
Runtime warning: invalid value encountered in subtract

### ISSUE THREAD

**Issue by dgoryeo** [ina-foss/inaSpeechSegmenter#79]
Please fill out this template for a bug report.

Make sure you ran the unit tests before submitting an issue and tell us if and where they fail.

## System information
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 11, conda env
- TensorFlow version: 2.14
- Python version: 3.11
- Running on GPU or CPU: GPU
- Using Docker:  NO

## System information required if using GPU acceleration
- output of command `nvidia-smi` :  CUDA 12.2
- output of command `python3 -c "import tensorflow as tf; print(tf.sysconfig.get_build_info()); print(tf.config.list_physical_devices('GPU'))"` :
- CUDA/cuDNN version : CUDA 11.8

## Current Behavior
Warning: 
\inaSpeechSegmenter\segmenter.py:80: RuntimeWarning: invalid value encountered in subtract
  data = (data - np.mean(data, axis=1).reshape((len(data), 1))) / np.std(data, axis=1).reshape((len(data), 1))

## Steps to Reproduce

1. Within python code just running the segmenter on any audio file. 
2.
3.
4.

**Comment by Rakibul73** [comment]
facing same error. tried in public mp3/mp4 file.. 
The label is extracted, but the entire audio is not detected. I believe where voice and background sounds are mixed together, not being detected correctly. Anybody have a better idea or solution ?? 

![image](https://github.com/ina-foss/inaSpeechSegmenter/assets/72851692/d9692337-491a-434e-9890-2ad240034ec6)

**Comment by DavidDoukhan** [comment]
Dear @dgoryeo and @Rakibul73 ,

1) The warning message you're experiencing is not an error : it simply occurs when the audio signal contain portions of empty signal >= 20ms. These situations are then correctly handled in the code and should not result in classification errors. While this behavior is not a real problem, I should acknowledge that it may be scary/concerning for end-users of this framework. Contributions consisting to suppress these scary warnings are welcome !

2) Concerning the voice mixed with background noise issues reported by @Rakibul73 : I guess this behavior is related to the difficulty of the chosen material which may happen : some signal portions being harder to analyse than others. However, I remind that recent audiovisual benchmarks comparing inaSpeechSegmenter to 6 other open-source software on audiovisual materials show the performances of this system are still very competitive, see https://aclanthology.org/2024.lrec-main.785/

**Comment by Rakibul73** [comment]
@DavidDoukhan I appreciate the clarification 😇 . Thank you also for updating to remove that scary runtime warning 😅

**Comment by DavidDoukhan** [comment]
the scary warnings are removed from the repo and pip package. issue is now closed
