### ISSUE TITLE
GPU is not being used

### ISSUE THREAD

**Issue by elieobeid7** [ina-foss/inaSpeechSegmenter#87]
We have a  Python application that uses this library, we host the application on AWS EC2, ubuntu,  g4dn.xlarge.  This server has NVIDIA Tesla GPU, we have NVIDIA drivers installed, we have `tensorflow[gpu]` installed and we also tried using `tensorflow` as well.

We want to downscale the server, therefore we're running tests to see how much GPU our application uses. In a previous Github issue, a user mentioned that in order to utilize GPU with this library, you need `tensorflow` installed.

I ran `watch -n 1 nvidia-smi` to monitor the GPU usage every second.

And I'm using this code

```
from inaSpeechSegmenter import Segmenter
seg = Segmenter()
data = seg(file_path)
```

I don't see any GPU usage on a 1h mp3 file, does this library use the GPU? If yes then how?

**Comment by DavidDoukhan** [comment]
could you try using pip install tensorflow[and-cuda] ?

**Comment by DavidDoukhan** [comment]
fixed.
inaspeechsegmenter now install cuda drivers from the pip repo
they used to be installed manually in earlier version
