### ISSUE TITLE
Reporting multiple warnings from keras and tensorflow

### ISSUE THREAD

**Issue by elieobeid7** [ina-foss/inaSpeechSegmenter#88]
The version im using

```
inaSpeechSegmenter==0.7.8
tensorflow==2.16.1
tensorflow-estimator==2.13.0
tensorflow-io-gcs-filesystem==0.31.0
keras==3.3.3
```

inaSpeechSegmenter is the only  packages that relies on tensorflow and keras in my application, I don't use tensorflow or keras for anything else.

I run my tests on windows 11 and the application runs on Ubuntu server from aws, the warnings are on both systems. Our previous server was  [g4dn.xlarge](https://instances.vantage.sh/aws/ec2/g4dn.xlarge) with nvidia NVIDIA T4 Tensor Core, now we downgraded to [m5a.xlarge](https://instances.vantage.sh/aws/ec2/m5a.xlarge) with no GPU same issues on both.

and my PC I have nvidia geforce gtx 1650

I'd like to report these warnings, the package is working fine those but I'm just seeing these warnings.

As soon as the app starts, before any code is executed, I see

```
 I tensorflow/core/util/port.cc:113] oneDNN custom operations are on.
 You may see slightly different numerical results due to floating-point round-off errors from
different computation orders. To turn them off, set the environment variable 

`TF_ENABLE_ONEDNN_OPTS=0`.
````

then when I run this code

```
from inaSpeechSegmenter import Segmenter
seg = Segmenter()
data = seg(file_path)

```

I see

```
venv\lib\site-packages\keras\src\layers\reshaping\reshape.py:39: UserWarning: 
Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, 
prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)
2024-11-13 13:46:37.793652: I tensorflow/core/platform/cpu_feature_guard.cc:210] This 
TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the 
appropriate compiler flags.
venv\lib\site-packages\inaSpeechSegmenter\segmenter.py:80: RuntimeWarning: invalid value 
encountered in subtract
  data = (data - np.mean(data, axis=1).reshape((len(data), 1))) / np.std(data, 
axis=1).reshape((len(data), 1))
venv\lib\site-packages\numpy\core\_methods.py:173: RuntimeWarning: invalid value
encountered in subtract
  x = asanyarray(arr - arrmean)
```
The library I'm using is running on CPU only since I haven't yet updated the package to the version that [supports GPU](https://github.com/ina-foss/inaSpeechSegmenter/issues/87).

**Comment by DavidDoukhan** [comment]
From my understanding, these warnings are related to tensorflow, and you may face most of them whatever program you use based on this version of tensorflow.
I would suggest to run inaSpeechSegmenter's unit tests and check if all of them behave correctly.
To do it: 
```
# clone git repository
$ git clone https://github.com/ina-foss/inaSpeechSegmenter.git
# create a python 3 virtual environement and activate it
$ virtualenv -p python3 env
$ source env/bin/activate
# install framework and dependencies
# you should use pip instead of setup.py for installing from source
$ cd inaSpeechSegmenter
$ pip install .
# check program behavior
$ python setup.py test
```
