### ISSUE TITLE
Segmentation takes too long ? 

### ISSUE THREAD

**Issue by Cloud299** [ina-foss/inaSpeechSegmenter#9]
Is there any way to make this segmenter load/run faster? It takes a long time to segment music even when the input file is small.

**Comment by DavidDoukhan** [comment]
Hi,

Here are few remarks related to the execution speed of script ina_speech_segmenter.py:
 
* Script initialization time lasts 3 seconds.
This incompressible time is required to load the neural network models.
Consequently, if you need to process several files, the most approproriate method consist to list them on the command line, to avoid loading the neural networks for each file to process:
ina_speech_segmenter.py -i file1.mp3 file2.mp3 .... fileN.mp4 -o outputdirectory

The execution time is:
* 6 minutes per hour of archive using CPU Intel Core i7-6700 (3.40 Ghz, 4 cores, 8 threads)
* 1 minute per hour of archive using Titan X Maxwell GPU

There are few tricks to make the processing time faster:
1) using @elechapt fork of inaSpeechSegmenter. This implements a thread parallelization method allowing to improve the processing time of a list of archives of 30%, using a GPU only
2) It may be possible to get rid of Keras and use the trained neural networks using a pure Tensorflow implementation, that may allow to improve the processing time of another 30%.

Regards,

**Comment by Cloud299** [comment]
"1 minute per hour of archive using Titan X Maxwell GPU".

What is the API for running segmentation on GPU instead of CPU ?

**Comment by DavidDoukhan** [comment]
You need to install the pip package tensorflow-gpu.
Please refer to tensorflow documentation if you need additional details
